### ISSUE TITLE
simulator support

### ISSUE THREAD

**Issue by Binusz** [speedchecker/speedchecker-sdk-ios#1]
Is there any plan to support Xcode iOS simulator? 
Maybe you can also publish distinct simulator-supported frameworks.

**Comment by vandrusik** [comment]
Have in plans, but without actual date/release number.

**Comment by Binusz** [comment]
Is that mean I shouldn't wait for it soon?

**Comment by vandrusik** [comment]
Yes, correct

**Comment by bogdanicc** [comment]
We've added support for the simulator, check the latest commit.
