### ISSUE TITLE
issue when build archive

### ISSUE THREAD

**Issue by dhruv-dhola** [speedchecker/speedchecker-sdk-ios#10]
hello sir i have been using this sdk from last 2 months and its very convenient and superb but when i build archive i get error like no such module speedcheckerSDk. but when i run project in debug mode its working fine do you have any idea why this is happening?

**Comment by bogdanicc** [comment]
If I understood you correctly, you are using a version from 2 months ago? Did you try the latest version? We tested it and didn't encounter the error you are describing.

**Comment by bogdanicc** [comment]
Closing the issue since no additional information was provided and we updated ways of distributing SDK.
