### ISSUE TITLE
Refactored Method Names?

### ISSUE THREAD

**Issue by kpolleck** [speedchecker/speedchecker-sdk-ios#12]
I tried to update my 2 or 3 month old app that uses your (very nice) SDK, but it failed to compile with many error messages about handling of sockets.  I downloaded your latest SDK, and that solved most of the problems, but it appears that you refactored several method names (e.g. internetTest(finish:) changed to internetTestFinish(result:)) and changed from .framework to .xcframework files.

Do you have a log of changes?  I couldn't find one, and I am wondering what else I might have missed.

**Comment by bogdanicc** [comment]
We renamed some methods when we exposed them to Objective-C, we don't have the changelog of this but we did update the [documentation](https://github.com/speedchecker/speedchecker-sdk-ios/wiki/API-documentation) to reflect the current state. Other than naming, there isn't any significant change in the way you should use SpeedcheckerSDK, although we did resolve few internal bugs and made SDK more stable.

We changed from .framework to .xcframework when we added support for both simulator and physical iOS devices. Until recently, we supported only physical iOS devices, so this is new change. All the setup is the same as with .framework.

We'll create changelog file in the future and try to list all important changes there.
