### ISSUE TITLE
Speed test stuck at last step in IOS 15

### ISSUE THREAD

**Issue by rajAppmetry** [speedchecker/speedchecker-sdk-ios#13]
**Issue**

SDK works really well till ios 14, but if we run it on IOS 15 it get stuck on the last step. In IOS 15 all the upload and download process are getting trigger and completes but ``internetTestFinish`` never gets called.

Also if we try to start the test again then it throws error as ``inProgress``.

We are using the latest sdk which points to xcode 13.3.1

**Steps to reproduce**

1. Clone the sample app
2. Run the Sample app in any ios 15 device
3. Trigger the speed test

**Comment by bogdanicc** [comment]
@rajAppmetry thank you for reporting this issue, it should be resolved now. We had to make some SSL changes on server side for iOS 15.4+.

Can you please give it another try and confirm that problem is resolved for you?

**Comment by kpolleck** [comment]
I didn't report this originally, but I am having the same problem on:
- iOS 15.5
- iPhone 11
- SDK files dated May 17, 2022 (Is there a way to check a version of the SDK?  Ideally, querying the version would be part of the API.)

When it fails, it reports "The request timed out"...

2022-06-19 22:45:55.144004-0400 kSpeedtest[39736:2166495] Task <A24A3E58-FA0F-4D2A-AD04-CEB1A6868CA0>.<2> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x282e5c480 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A24A3E58-FA0F-4D2A-AD04-CEB1A6868CA0>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A24A3E58-FA0F-4D2A-AD04-CEB1A6868CA0>.<2>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://www.speedcheckerapi.com/TakenTests.svc/json/SaveMobileTakenTest, NSErrorFailingURLKey=https://www.speedcheckerapi.com/TakenTests.svc/json/SaveMobileTakenTest, _kCFStreamErrorDomainKey=4}
HAH: 14.392829895019531
14.39319396018982
SaveMobileTakenTest

I'm not sure if I need to set up background processing.  Would this problem occur if background processing isn't set up correctly?

Regarding a DIFFERENT problem with SSL, I set this in Info.plist as a work-around.  Is this still required?
    <key>NSAppTransportSecurity</key>
      <dict>
          <key>NSAllowsArbitraryLoads</key>
          <true/>
      </dict>

**Comment by bogdanicc** [comment]
@kpolleck this looks like slightly different problem which shouldn't be related to iOS version, as original issue. You are getting `-1001 "The request timed out."` which suggest that server didn't respond in given time. This could happen if you had bad connection on client side, or if our server had some issue and didn't respond. Does this error still happens to you? because it's working as expected for us.

We did find out that in case of this timeout delegate methods are not being called as expected (neither `internetTestFinish` nor `internetTestError`). We will upload new SDK version with fix for this and ping you.

> Is there a way to check a version of the SDK? Ideally, querying the version would be part of the API.

You can use `SCLogger.sdkVersion` to get current SDK version.

> I'm not sure if I need to set up background processing. Would this problem occur if background processing isn't set up correctly?

You don't need background processing.

> Regarding a DIFFERENT problem with SSL, I set this in Info.plist as a work-around. Is this still required?

Original problem with SSL is solved, you don't need to use that work-around anymore.

**Comment by kpolleck** [comment]
@bogdanicc Thanks for the quick responses.  I only get to my hobby programming a bit each week, so I haven't yet followed up on these things.

I do expect that timeouts happened for some of these cases, but I was expecting  that you would return an error at some point.  In testing it previously, even if I manually stopped the test, it wouldn't start a subsequent test.  To reset things to work again, I would have to:

    internetTest = nil
    internetTest = InternetSpeedTest(delegate: self)

Have you uploaded your SDK updates for this?

**Comment by kpolleck** [comment]
@bogdanicc Have you been able to update your SDK yet?

>> We did find out that in case of this timeout delegate methods are not being called as expected (neither internetTestFinish nor internetTestError). We will upload new SDK version with fix for this and ping you.

**Comment by bogdanicc** [comment]
@kpolleck sorry for delay, this bug should be resolved now. https://github.com/speedchecker/speedchecker-sdk-ios/commit/253323e8b7f3851ba3e61ca1dbb865fa74b3c0e2
