### ISSUE TITLE
What if we don't have Permitted Background Task Scheduler Identifiers

### ISSUE THREAD

**Issue by kpolleck** [speedchecker/speedchecker-sdk-ios#14]
It we don't set Permitted Background Task Scheduler Identifiers to com.speedchecker.bg tests, what behavior would we see?

I tried changing it just to see, and I'm not seeing any difference.  However, I'm launching each test from the foreground, so maybe it matters only when the speedchecker starts in the background?  (I'm just guessing.)

**Comment by bogdanicc** [comment]
@kpolleck setting Permitted Background Task Scheduler Identifiers is only required if you are using `BackgroundTest` class which enables automatic background tests functionality (available for paid version only). If you are using only regular speed test functionality (`InternetSpeedTest` class) you can completely ignore background setup instructions.

BGTaskSchedulerPermittedIdentifiers are required to support [scheduling of background tasks](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler).
