### ISSUE TITLE
Can you limit data transfer?

### ISSUE THREAD

**Issue by kpolleck** [speedchecker/speedchecker-sdk-ios#15]
I've noticed that when I have a great 4G celluar (WAN) connection, my data usage on a single speed test can approach 100MB...which is way over what I want to consume for my little sample program used to find weak signal/data rate spots.  That is, I'm trying to determine if a location provides only 2-3mbps (which is fine for most applications)--or well less or more than that.  ...but whether it provides 10mbps, 20mbps, or 30+mbps is mostly immaterial from my goal.  All of those rates are perfectly fine, and I would rather not consume the extra bandwidth to learn something I don't really need to know.

Suggestion:  Could you add a configurable limit?  This would also reduce the load on your servers.  Admittedly, I'm using the free SDK, so I cannot complain, but if a 5 second test shows a certain level, perhaps we don't need the 10 second test.

Thanks!

**Comment by jezowicz** [comment]
Our Basic version allows changing parameters of the test such as the time of download / upload part, thread settings, warm-up phase etc
