### ISSUE TITLE
Support Swift 5.5

### ISSUE THREAD

**Issue by gixdev** [speedchecker/speedchecker-sdk-ios#2]
> Failed to build module 'SpeedcheckerSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.

**Comment by vandrusik** [comment]
Please download newest SDK files from subfolder Xcode13

**Comment by kpolleck** [comment]
I had the same error.  To be explicit with the steps needed to correct this, the files I needed were already in my download of speedchecker-sdk-ios-master...just not in the "Sample in Swift" directory.

I just had to copy the directories in
     speedchecker-sdk-ios-master/Framework/xcode13.2.1/*.framework
to
     speedchecker-sdk-io-master/Sample in Swift/SCSDK/*.framework
     
(I was confused, though, because the downloaded "Sample in Swift" subdirectories seemed to have a Dec 31, 2021 date, so I assumed they had been updated for Swift v5.5...but then, upon looking in the files (such as:
     Sample in Swift/DataCompression.framework/Modules/DataCompresion.swiftmodule/arm64-apple-ios.swiftinterface
I could see that they were built with Swift v5.4.2.)

**Comment by kpolleck** [comment]
A question for the author:  Why does the SpeedcheckerSDK Sample.xcodeproj list "CryptoSwift.framework"?  Am I missing something?  I didn't seem to be in the downloaded frameworks.

**Comment by vandrusik** [comment]
Thank you for comments, we will update framework files in the sample app, and exclude CryptoSwift too (it was used early)

**Comment by BilalPervez** [comment]
@kpolleck @vandrusik 
what can be the issue or i'm missing something? 
When i make build in Xcode 13. 2.1(13C100) of my already existing code (project) by adding framework from folder Xcode13.2.1 the build still shows same above error,

**"Failed to build module 'Socket'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK."**

**'Socket' inherits from itself**
**'SocketReader' is not a member type of class 'Socket.Socket'**
**'SocketWriter' is not a member type of class 'Socket.Socket'**

But creating new project on same Xcode 13.2.1(13C100) version it works and run the build.

**Comment by vandrusik** [comment]
@BilalPervez try please delete DerivedData, clean the build, double-check that you copied correct version binaries, and then rebuild your project

**Comment by BilalPervez** [comment]
@vandrusik Why we need to replace frameworks for different Xcode versions?
As we working in a team and we are facing issues of "Support Swift 5.5 **OR** Support Swift 5.5.2" due to different Xcode versions. Any solution to get rid of this? other than that we all update on Latest Xcode versions.

**Comment by bogdanicc** [comment]
This issue is no longer relevant. We now distribute .xcframework files built with the `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` parameter, ensuring future binary compatibility.
