### ISSUE TITLE
Cannot distribute to the AppStore because Frameworks are missing CFBundleVersion in Info.plist

### ISSUE THREAD

**Issue by itpropmn07** [speedchecker/speedchecker-sdk-ios#21]
Hello, I am currently embedding the latest version (1.8.12) of the SpeedChecker SDK into my application, it works very well. But when uploading to the AppStore, Xcode reports an error missing CFBundleVersion in the Info.plist file in the frameworks of the SpeedChecker SDK, so I can’t distribute it to the AppStore. I am using Xcode 15. Please fix it. Thanks.

![Screenshot 2023-09-23 at 05 21 15](https://github.com/speedchecker/speedchecker-sdk-ios/assets/72042507/f6305605-052e-46ae-a1dd-42c2f5dbeff0)

**Comment by bogdanicc** [comment]
Thank you for bringing this to our attention.

I've successfully reproduced the issue in Xcode 15 and have released new SDK version 1.8.13 with the necessary fix. Could you please verify and let us know if it resolves the problem for you?

**Comment by itpropmn07** [comment]
Hello, thank you for fixing this bug quickly, I can confirm that version 1.8.13 was able to distribute to the App Store successfully.
