### ISSUE TITLE
CocoaPods and version 1.8.13

### ISSUE THREAD

**Issue by Maxim199901** [speedchecker/speedchecker-sdk-ios#22]
Hi, please tell me when version 1.8.13 will be available via CocoaPods, I have version cocoapods 1.13.0, gives you a maximum of 1.5.66

**Comment by bogdanicc** [comment]
Hi, I just checked and version 1.8.13 is indeed available via CocoaPods.

There are few things that you can check:
1. Your local CocoaPods spec repo might be outdated. Try running `pod repo update` and `pod install` to updated it.
2. If you previously installed version 1.5.66, it might be locked in your `Podfile.lock`, try deleting it from there and running `pod install`.
3. Ensure that you don't have a specific lower version set for the library in your `Podfile`.

**Comment by Maxim199901** [comment]
Hi, You were right, I have an outdated local cocoapods, the first point helped me. Thanks)
