### ISSUE TITLE
Warnings Encountered When Submitting iOS App with SpeedChecker Framework Using Xcode 16 RC

### ISSUE THREAD

**Issue by itpropmn07** [speedchecker/speedchecker-sdk-ios#24]
Hello, 

I am currently using the latest version of SpeedChecker, version 2.0.4. It works very well, but when I submit it to the App Store, although the process completes normally, there are some warnings as shown in the image. I hope you can fix it soon. This issue occurs when submitting to the App Store using Xcode 16 RC (the latest version currently). 

Thank you.

![Screenshot 2024-09-13 at 04 26 20](https://github.com/user-attachments/assets/2dc3ba54-24ee-435e-8cd2-32d769016c2c)

**Comment by bogdanicc** [comment]
Thanks for reporting this issue. Please check new version (2.0.5) which should resolve it.
