### ISSUE TITLE
Asset validation failed (bitcode)

### ISSUE THREAD

**Issue by DanialOvcharenko** [speedchecker/speedchecker-sdk-ios#25]
Hello,

I am currently using the latest version of SpeedChecker, version 2.0.4. It works very well, but when I submit it to the App Store, although the process not completes because errors, there are errors and warnings as shown in the image. I hope you can fix it soon. This issue occurs when submitting to the App Store using Xcode 16, macOS Sequoia (15.0).

Thank you.

<img width="755" alt="Знімок екрана 2024-11-12 о 17 01 35" src="https://github.com/user-attachments/assets/74e7a376-25a8-4ac3-b2f6-b6006a0272dd">

**Comment by bogdanicc** [comment]
Thanks for reporting this issue. Please check new version (2.0.5) which should resolve it.
