### ISSUE TITLE
Support Swift 5.5.2 (shipped with Xcode 13.2)

### ISSUE THREAD

**Issue by theoks** [speedchecker/speedchecker-sdk-ios#3]
`Failed to build module 'SpeedcheckerSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.`

**Comment by vandrusik** [comment]
SDK is updated, please take files from folder xcode13.2
