### ISSUE TITLE
How long should a test take?

### ISSUE THREAD

**Issue by kpolleck** [speedchecker/speedchecker-sdk-ios#5]
When running your sample app, it seems to take about 20 seconds to get a result back?  Is that what I should expect?

Is there a way to shorten the test?  ...maybe by running a test with less data...or only one of the three tests (download/upload/latency)?  (I realize that the results would be more variable.)

My goal is to learn where they dead spots are where I typically drive.  I know of two just by streaming video, but I can drive through both in less than 20 seconds.  If I could get a test that runs in, say, 5 seconds, I could pinpoint the center of the dead spot better.

**Comment by vandrusik** [comment]
Yes, 20 seconds is an usual time to get results.
In paid version you could manage options, like upload/download tests duration, or even ignore some part

**Comment by garridozh** [comment]
will be possible set just the upload test speed and to change the duration time to 5 seconds (for example) in paid version? Is it possible to pay for it month by month?

**Comment by vandrusik** [comment]
@garridozh yes, it's possible to change times and switch off all except upload test.
about payment, please contact via form
https://www.speedchecker.com/contact-us.html
