### ISSUE TITLE
bitcode bundle could not be generated

### ISSUE THREAD

**Issue by rajani9288** [speedchecker/speedchecker-sdk-ios#6]
hi I am getting error while archive. you have solution or you can give pod install.

bitcode bundle could not be generated.

bitcode bundle could not be generated because '/Users/add/Library/Developer/Xcode/DerivedData/appName-csqbtphcvesaisfgeqysvxuwieai/Build/Products/QA-iphoneos/Algorithms.o' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/add/Library/Developer/Xcode/DerivedData/appName-csqbtphcvesaisfgeqysvxuwieai/Build/Products/QA-iphoneos/Algorithms.o' for architecture arm64

**Comment by vandrusik** [comment]
Hi,
The SDK has enabled bitcode option.
Why you think that this error related to SpeedcheckerSDK? I see that it complains about Algorithms.o

**Comment by rajani9288** [comment]
because I was enable bitcode. so error may be different.
 
but i reverse  my Xcode setting. after that its running fine on phone but in archive it show this error. 

bitcode bundle could not be generated because '/Users/add/Desktop/HFCLGIT/appName/SCSDK/SpeedcheckerReportSDK.framework/SpeedcheckerReportSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/add/Desktop/HFCLGIT/appName/SCSDK/SpeedcheckerReportSDK.framework/SpeedcheckerReportSDK' for architecture arm64

please check above issue and help me out.

**Comment by rajani9288** [comment]
hi even your sample cade also not able to archive. check this I am getting this error.

bitcode bundle could not be generated because '/Users/add/Downloads/speedchecker-sdk-ios-master-4/Sample in Swift/SCSDK/SpeedcheckerSDK.framework/SpeedcheckerSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/add/Downloads/speedchecker-sdk-ios-master-4/Sample in Swift/SCSDK/SpeedcheckerSDK.framework/SpeedcheckerSDK' for architecture arm64

**Comment by rajani9288** [comment]
please let me know if find any solution.

**Comment by vandrusik** [comment]
Hi guys, please try with a new files, I just updated them

**Comment by rajani9288** [comment]
Thanks for quick reply
