### ISSUE TITLE
Code run but get this error 

### ISSUE THREAD

**Issue by TeksunNj** [speedchecker/speedchecker-sdk-ios#7]
SpeedcheckerSDK Sample[622:31284] [Client] {"msg":"#NullIsland Either the latitude or longitude was exactly 0! That's highly unlikely", "latIsZero":0, "lonIsZero":0}

SpeedcheckerSDK Sample[622:31746] A location manager (0x12c004500) was created on a dispatch queue executing on a thread other than the main thread.  It is the developer's responsibility to ensure that there is a run loop running on the thread on which the location manager object is allocated.  In particular, creating location managers in arbitrary dispatch queues (not attached to the main queue) is not supported and will result in callbacks not being received.

If you could please guide me further regarding the above error 
it's a free version test.
Xcode :- 13.0 
Testing in iPhone device :- X

**Comment by rajani9288** [comment]
you need to manage main thread and background thread. after every delegate callback run your code on main thread

**Comment by TeksunNj** [comment]
@rajani9288,  Thank you for your quick response

Already I manage code in the main thread and background thread both 
still, I'm not getting a response  
can you possibly share here the code for the Swift version with the main thread or update the branch

**Comment by vandrusik** [comment]
@TeksunNj could you try with at least Xcode 13.1? 
Previous files were not updated for some time, fresh versions are made for 13.1 and later

**Comment by TeksunNj** [comment]
@vandrusik Thank you for your quick response and support 
 13.2 SDK working fine as of now.
